// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'run flutterfire configure from the Flutter project directory.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'run flutterfire configure from the Flutter project directory.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run flutterfire configure from the Flutter project directory.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBELOfYVwijYktrxwQ5YNing3HqE-x7RI',
    appId: '1:407362360050:web:b5e3612dad5ccb8dcff66b',
    messagingSenderId: '407362360050',
    projectId: 'food-application-9e7f2',
    authDomain: 'food-application-9e7f2.firebaseapp.com',
    storageBucket: 'food-application-9e7f2.firebasestorage.app',
    measurementId: 'G-1846R9RXDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPxZ1Bo20HDbWIQXEGoDKVxM39tjiUzME',
    appId: '1:407362360050:android:bee614750fc3aa26cff66b',
    messagingSenderId: '407362360050',
    projectId: 'food-application-9e7f2',
    storageBucket: 'food-application-9e7f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3rPYYHrord9DUPtKoW7bo01zrxgoCGRI',
    appId: '1:407362360050:ios:8eeab9cfe9202491cff66b',
    messagingSenderId: '407362360050',
    projectId: 'food-application-9e7f2',
    storageBucket: 'food-application-9e7f2.firebasestorage.app',
    iosBundleId: 'com.example.foodApplication',
  );
}
